powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\GIMAP.png Png map .\resources.binary.image.map.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\GIMINIMAP_CAILB.png Png cailb .\image\cailb\resources.binary.image.cailb.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\GISTARTEMPLATE.bmp Bmp star .\image\star\resources.binary.image.star.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\GIPAIMON.bmp Bmp paimon .\image\paimon\resources.binary.image.paimon.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid_.bmp Bmp uid_ .\image\uid\resources.binary.image.uid_.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid0.bmp Bmp uid0 .\image\uid\resources.binary.image.uid0.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid1.bmp Bmp uid1 .\image\uid\resources.binary.image.uid1.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid2.bmp Bmp uid2 .\image\uid\resources.binary.image.uid2.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid3.bmp Bmp uid3 .\image\uid\resources.binary.image.uid3.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid4.bmp Bmp uid4 .\image\uid\resources.binary.image.uid4.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid5.bmp Bmp uid5 .\image\uid\resources.binary.image.uid5.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid6.bmp Bmp uid6 .\image\uid\resources.binary.image.uid6.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid7.bmp Bmp uid7 .\image\uid\resources.binary.image.uid7.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid8.bmp Bmp uid8 .\image\uid\resources.binary.image.uid8.h 
powershell -ExecutionPolicy Bypass -File .\image_to_binary.ps1 ..\..\..\resource\png\uid9.bmp Bmp uid9 .\image\uid\resources.binary.image.uid9.h 
