function(parse_version_file version_file)
    file(READ "${version_file}" version_file_content)
    string(STRIP "${version_file_content}" version_file_content)
    message(STATUS "当前编译版本: ${version_file}: ${version_file_content}")
    string(REPLACE "." ";" version_content_list "${version_file_content}")
    list(GET version_content_list 0 version_major)
    list(GET version_content_list 1 version_minor)
    list(GET version_content_list 2 version_patch)
    set(VERSION_MAJOR ${version_major} PARENT_SCOPE)
    set(VERSION_MINOR ${version_minor} PARENT_SCOPE)
    set(VERSION_PATCH ${version_patch} PARENT_SCOPE)
    message(STATUS "parse_version_file: VERSION_MAJOR: ${version_major}")
endfunction(parse_version_file version_file)